application: powerfood2011
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media/css
  static_dir: media/css
  expiration: '0'

- url: /media
  static_dir: media
  expiration: '0'

- url: /favicon\.ico
  static_files: media/favicon.ico
  upload: media/favicon\.ico

- url: /.*
  script: djangoappengine/main/main.py
  secure: always
